# Sentiment Analysis Project Configuration

# Data Configuration
data:
  sample_size: 1000
  test_size: 0.2
  random_state: 42
  
# Text Preprocessing Configuration
preprocessing:
  remove_stopwords: true
  use_stemming: false
  use_lemmatization: true
  max_features: 5000
  ngram_range: [1, 2]
  min_token_length: 2

# Traditional ML Models Configuration
traditional_models:
  logistic_regression:
    max_iter: 1000
    random_state: 42
    solver: 'liblinear'
  
  svm:
    kernel: 'linear'
    probability: true
    random_state: 42
  
  naive_bayes:
    alpha: 1.0
  
  random_forest:
    n_estimators: 100
    random_state: 42
    max_depth: null

# Transformer Models Configuration
transformer_models:
  default_model: 'cardiffnlp/twitter-roberta-base-sentiment-latest'
  alternatives:
    - 'distilbert-base-uncased-finetuned-sst-2-english'
    - 'nlptown/bert-base-multilingual-uncased-sentiment'
    - 'cardiffnlp/twitter-roberta-base-sentiment'
  
  # Model loading parameters
  return_all_scores: true
  use_fast_tokenizer: true

# Vectorization Configuration
vectorization:
  tfidf:
    max_features: 5000
    ngram_range: [1, 2]
    stop_words: 'english'
    lowercase: true
    min_df: 1
    max_df: 0.95
  
  count:
    max_features: 5000
    ngram_range: [1, 2]
    stop_words: 'english'
    lowercase: true
    min_df: 1
    max_df: 0.95

# Model Evaluation Configuration
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
  cross_validation:
    cv_folds: 5
    scoring: 'accuracy'

# File Paths Configuration
paths:
  data_dir: './data'
  models_dir: './models'
  notebooks_dir: './notebooks'
  results_dir: './results'
  logs_dir: './logs'

# Visualization Configuration
visualization:
  figure_size: [10, 6]
  color_palette: 'viridis'
  save_plots: true
  plot_format: 'png'
  dpi: 300

# Logging Configuration
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_to_file: true
  log_file: 'sentiment_analysis.log'

# API Configuration (for future deployment)
api:
  host: '0.0.0.0'
  port: 8000
  debug: false
  max_text_length: 1000
  rate_limit: 100  # requests per minute

# Performance Configuration
performance:
  n_jobs: -1  # Use all available processors
  batch_size: 32
  cache_models: true
  parallel_processing: true
